# The run config is used for both run mode and debug mode

[[configs]]
# the name of this task
name = "start"

# the type of the debugger. If not set, it can't be debugged but can still be run
# type = "lldb"

# the program to run
program = "npm"

# the program arguments, e.g. args = ["arg1", "arg2"], optional
args = ['start']

# current working directory, optional
# cwd = "${workspace}"

# environment variables, optional
# [configs.env]
# VAR1 = "VAL1"
# VAR2 = "VAL2"

# task to run before the run/debug session is started, optional
# [configs.prelaunch]
# program = "cargo"
# args = [
#   "build",
# ]

[[configs]]
# the name of this task
name = "run api"

# the type of the debugger. If not set, it can't be debugged but can still be run
# type = "lldb"

# the program to run
program = "node"

# the program arguments, e.g. args = ["arg1", "arg2"], optional
args = ['./api/app.js']

# current working directory, optional
# cwd = "${workspace}"

# environment variables, optional
# [configs.env]
# VAR1 = "VAL1"
# VAR2 = "VAL2"

# task to run before the run/debug session is started, optional
# [configs.prelaunch]
# program = "cargo"
# args = [
#  